"""
Pre and Post Pulse Analysis Tools (PPPAT)

PPPAT is a graphical tool which helps validating the WEST pulse settings
which is generated by XEdit and DCS. PPPAT also aims to check that the
WEST Operational Instructions (WOI) are respected, before the pulse but also
once the pulse has been made.

@authors: J.Hillairet, based on C.Reux version
"""
# Running this script will launch PPPAT's graphical user interface
if __name__ == '__main__':
    import sys
    from pppat import app

    sys.exit(app.run(sys.argv))
