# -*- coding: utf-8 -*-
"""
PPPAT - Pre pulse display ui
"""
from qtpy.QtWidgets import (QWidget, QGridLayout, QRadioButton, QGroupBox,
                            QVBoxLayout, QTextBrowser, QLabel, QPushButton,
                            QFormLayout, QLineEdit, QFileDialog, QComboBox,
                            QErrorMessage, QTableView, QAbstractItemView,
                            QTableWidget, QTableWidgetItem, QHeaderView)
from qtpy.QtGui import QIntValidator, QFont
from qtpy.QtCore import Slot

import logging
logger = logging.getLogger(__name__)


class PrePulseDisplayWidget(QWidget):
    """
    Pre-Pulse Display GUI
    
    This tool display the various waveforms generated by the session leader.
    """
    
    def __init__(self):
        