# -*- coding: utf-8 -*-
"""
PPPAT - Pre pulse display ui
"""
from qtpy.QtWidgets import (QWidget, QGridLayout, QRadioButton, QGroupBox,
                            QVBoxLayout, QTextBrowser, QLabel, QPushButton,
                            QFormLayout, QLineEdit, QFileDialog, QComboBox,
                            QErrorMessage, QTableView, QAbstractItemView,
                            QTableWidget, QTableWidgetItem, QHeaderView)
from qtpy.QtGui import QIntValidator, QFont, QIcon
from qtpy.QtCore import Slot

import logging
logger = logging.getLogger(__name__)


class PrePulseDisplayWidget(QWidget):
    """
    Pre-Pulse Display GUI
    
    This tool display the various waveforms generated by the session leader.
    """
    
    def __init__(self, parent=None):
        super(PrePulseDisplayWidget, self).__init__(parent=parent)

        self.push_controlroom = QPushButton("Control Room")
        self.push_controlroom.setEnabled(False) # disable per default
        self.push_controlroom.setIcon(QIcon('resources/icons/ui/line-chart-fill_.png'))
        layout = QVBoxLayout()
        layout.addWidget(self.push_controlroom)
        
        self.push_bigpicture = QPushButton("Big Picture")
        # self.push_bigpicture.setEnabled(False) # disable per default
        self.push_bigpicture.setIcon(QIcon('resources/icons/ui/line-chart-fill_.png'))

        layout.addWidget(self.push_bigpicture)
        

        
        self.setLayout(layout)
        